{
  "name": "cni0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "nodename": "master-01",
      "type": "calico",
      "etcd_endpoints": "https://172.17.8.101:2379",
      "etcd_cert_file": "/etc/ssl/etcd/ssl/etcd.pem",
      "etcd_key_file": "/etc/ssl/etcd/ssl/etcd-key.pem",
      "etcd_ca_cert_file": "/etc/ssl/etcd/ssl/ca.pem",
      "log_level": "info",
      "ipam": {
        "type": "calico-ipam"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/kubernetes/calico-kubeconfig.yaml"
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
