admin:
  ip: 0.0.0.0
  port: 9991

namers:
- kind: io.l5d.fs
  rootDir: /disco

storage:
  kind: io.l5d.inMemory
  namespaces:
    etcd: |
      /cluster   => /#/io.l5d.fs;
      /svc       => /cluster;
      /svc/etcd => /cluster/etcd;
    apiserver: |
      /cluster   => /#/io.l5d.fs;
      /svc       => /cluster;
      /svc/apiserver => /cluster/apiserver;
    vault: |
      /cluster   => /#/io.l5d.fs;
      /svc       => /cluster;
      /svc/vault => /cluster/vault;
    dashboard: |
      /cluster   => /#/io.l5d.fs;
      /svc       => /cluster;
      /svc/dashboard => /cluster/dashboard;
    prometheus: |
      /cluster   => /#/io.l5d.fs;
      /svc       => /cluster;
      /svc/prometheus => /cluster/prometheus;
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
